### ISSUE TITLE
Problem with selecting XML Radio Button in FileMaker 16

### ISSUE THREAD

**Issue by HansReinJacobi** [rwu2359/FMPddr#1]
In FileMaker 16 the script gives me an error when it's trying to select the XML Radio Button.
See screenshot:
I've Solved it by replacing the line: 
click checkbox 3 of window "Database Design Report" 
with 
click radio button 2 of window "Database Design Report"
![screen shot 2017-06-15 at 17 23 44](https://user-images.githubusercontent.com/29460629/27188841-c21fac56-51ef-11e7-81ac-c587c4407dca.png)

**Comment by rwu2359** [comment]
Thanks Hans, I will look at amending the AppleScript to look at the version..

**Comment by rwu2359** [comment]
@HansReinJacobi code fixed in v1.5
